version: "3.3"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: db01

  api:
    restart: always
    image: kohonski/sc2league-server_backend
    container_name: api
    links:
      - db
    volumes:
      - static:/var/www/static
    expose:
      - "8000"

  nginx:
    restart: always
    image: kohonski/sc2league-server_nginx
    container_name: nginx
    environment:
      - USE_LETSENCRYPT=T
      - DOMAIN
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - api

volumes:
  static: 
