version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: db01

  api:
    image: kohonski/sc2league-server_backend
    build: .
    container_name: api
    links:
      - db
    volumes:
      - ./tests:/application/tests/
      - static:/var/www/static
    expose:
      - "8000"

  nginx:
    image: kohonski/sc2league-server_nginx
    container_name: nginx
    environment:
      - USE_LETSENCRYPT=F
      - DOMAIN=localhost
    build: ./config/nginx/
    volumes:
      - ./config/nginx/ssl:/certificates
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - api

volumes:
  static: 
