version: "3.3"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: db01
  web:
    restart: always
    build: .
    container_name: django01
    links:
      - db
    volumes:
      - ./src:/src
      - static:/var/www/static
    expose:
      - "8000"
  nginx:
    build: ./config/nginx/
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - web

volumes:
  static: 
