version: "2"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: db01
  web:
    restart: always
    build: .
    container_name: django01
    links:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
