version: "2"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: db01
  web:
    restart: always
    build: .
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py startserver 0.0.0.0:8000"
    container_name: django01
    links:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
