setup(
    name='sc2league-server',
    version='0.0.1',
    author='Nic Kohonski',
    author=email='cybercoder91@aol.com',
    url='https://gitbug.com/biddellns/sc2league-server',
    packages=[],
    license='GPL-3.0',
    zip_safe=False,
    classifiers=[
        'Development Status :: 1 - Alpha',
        'Environment :: Console',
        'Framework :: Django :: 1.11',
        'Intended Audience :: SC2 Players',
        'Natural Language :: English',
        'License :: OSI Approved :: GPL-3.0 License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: SC2 Leagues',
    ], 
)
